controllers_web:
    resource: ../../src/Controller/Web
    type: annotation
    prefix: '/'
    name_prefix: 'web_'

controllers_api:
    resource: ../../src/Controller/Api
    type: annotation
    prefix: '/api'
    name_prefix: 'api_'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
